using System.Text;
using Novolis.CodeGen.Bindings;

namespace Novolis.Audio.CodeGen;

internal static class AudioInteropEmitter
{
    private static string Utf8Param(AudioInteropPolicy policy) =>
        policy.UseDisableRuntimeMarshalling ? "[MarshalUsing(typeof(Utf8StringMarshaller))] " : "";

    public static string Emit(InteropExportsFragment fragment, string manifestSha256, AudioInteropPolicy policy)
    {
        if (fragment.Imports.Count == 0)
            throw new InvalidOperationException("Manifest has no imports.");

        var sortedImports = fragment.Imports.OrderBy(i => i.Name, StringComparer.Ordinal).Select(AudioManifestMapping.ToImport).ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Regenerate: {CodegenHeaders.RegenerateHint}");
        sb.AppendLine($"// ManifestSha256: {manifestSha256}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        if (policy.UseDisableRuntimeMarshalling)
            sb.AppendLine("using System.Runtime.InteropServices.Marshalling;");
        sb.AppendLine("using Novolis.Audio.Interop;");
        sb.AppendLine();
        sb.AppendLine("namespace Novolis.Audio.Interop;");

        var dll = string.IsNullOrEmpty(fragment.DllName) ? "novolis_audio" : fragment.DllName;
        sb.AppendLine();
        sb.AppendLine("/// <summary>Low-level novolis_audio entry points (manifest-generated <c>[LibraryImport]</c>).</summary>");
        sb.AppendLine("internal static partial class NovolisAudioNative");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string AudioDll = \"{dll}\";");
        sb.AppendLine();

        foreach (var imp in sortedImports)
            EmitImport(sb, imp, policy);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitImport(StringBuilder sb, AudioImport import, AudioInteropPolicy policy)
    {
        var name = import.Name!;
        var template = import.Template!;
        var suppress = policy.ShouldSuppressGcTransition(import);
        var utf8 = template.Contains("string_utf8", StringComparison.Ordinal);

        switch (template)
        {
            case "void_void":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}();");
                break;
            case "bool_void":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine("    [return: MarshalAs(UnmanagedType.I1)]");
                sb.AppendLine($"    internal static partial bool {name}();");
                break;
            case "void_float":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(float volume);");
                break;
            case "void_nint":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(nint handle);");
                break;
            case "bool_nint":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine("    [return: MarshalAs(UnmanagedType.I1)]");
                sb.AppendLine($"    internal static partial bool {name}(nint handle);");
                break;
            case "nint_string_utf8":
                Li(sb, suppress, utf8: true, policy);
                sb.AppendLine($"    internal static partial nint {name}({Utf8Param(policy)}string filePath);");
                break;
            case "void_nint_float":
                Li(sb, suppress, utf8, policy);
                sb.AppendLine($"    internal static partial void {name}(nint handle, float volume);");
                break;
            default:
                throw new InvalidOperationException($"Unknown interop template '{template}' for {name}.");
        }

        sb.AppendLine();
    }

    private static void Li(StringBuilder sb, bool suppressGcTransition, bool utf8, AudioInteropPolicy policy)
    {
        if (utf8)
            LiUtf8(sb, suppressGcTransition, policy);
        else
            LiBlittable(sb, suppressGcTransition, policy);
    }

    private static void LiBlittable(StringBuilder sb, bool suppressGcTransition, AudioInteropPolicy policy)
    {
        if (suppressGcTransition && !policy.UseDisableRuntimeMarshalling)
            sb.AppendLine("    [LibraryImport(AudioDll, SuppressGCTransition = true)]");
        else
            sb.AppendLine("    [LibraryImport(AudioDll)]");
    }

    private static void LiUtf8(StringBuilder sb, bool suppressGcTransition, AudioInteropPolicy policy)
    {
        if (policy.UseDisableRuntimeMarshalling)
            LiBlittable(sb, suppressGcTransition, policy);
        else if (suppressGcTransition)
            sb.AppendLine("    [LibraryImport(AudioDll, StringMarshalling = StringMarshalling.Utf8, SuppressGCTransition = true)]");
        else
            sb.AppendLine("    [LibraryImport(AudioDll, StringMarshalling = StringMarshalling.Utf8)]");
    }
}
