using System.Text;

namespace Novolis.Audio.CodeGen;

internal static class FacadeEmitter
{
    public static string EmitType(
        FacadeTypeDefinition type,
        string manifestSha256,
        string? facadeMethodImpl = null)
    {
        var useInlining = string.Equals(facadeMethodImpl, "AggressiveInlining", StringComparison.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Regenerate: {CodegenHeaders.RegenerateHint}");
        sb.AppendLine($"// ManifestSha256: {manifestSha256}");
        sb.AppendLine("#nullable enable");

        foreach (var u in type.Usings ?? [])
            sb.AppendLine($"using {u};");

        if (useInlining)
            sb.AppendLine("using System.Runtime.CompilerServices;");

        sb.AppendLine();
        sb.AppendLine($"namespace {type.Namespace};");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(type.TypeSummary))
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {EscapeXml(type.TypeSummary)}");
            sb.AppendLine("/// </summary>");
        }

        sb.AppendLine($"public static partial class {type.Name}");
        sb.AppendLine("{");

        foreach (var method in type.Methods ?? [])
        {
            if (!string.IsNullOrWhiteSpace(method.Summary))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {EscapeXml(method.Summary)}");
                sb.AppendLine("    /// </summary>");
            }

            if (useInlining)
                sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");

            sb.AppendLine($"    public static {method.Signature.Trim()} => {method.Body.Trim().TrimEnd(';')};");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);
}
