using System.Security.Cryptography;
using System.Text;
using Novolis.Audio.Manifests;

namespace Novolis.Audio.CodeGen;

internal static class SpeechModelCatalogEmitter
{
    public static string Emit(string manifestSha256)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Regenerate: {CodegenHeaders.RegenerateHint}");
        sb.AppendLine($"// ManifestSha256: {manifestSha256}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Novolis.Audio.Voice;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Sherpa-ONNX speech engine kind for a bundled model.</summary>");
        sb.AppendLine("public enum SpeechModelEngine");
        sb.AppendLine("{");
        foreach (var engine in Enum.GetValues<SpeechModelEngineKind>())
        {
            sb.AppendLine($"    /// <summary>{EscapeXml(engine.ToString())}.</summary>");
            sb.AppendLine($"    {engine} = {Convert.ToInt32(engine)},");
        }
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Metadata for a bundled speech model declared in the speech models manifest.</summary>");
        sb.AppendLine("public readonly record struct BundledSpeechModel(");
        sb.AppendLine("    SpeechModelProfile Profile,");
        sb.AppendLine("    SpeechModelEngine Engine,");
        sb.AppendLine("    string RepoFolder,");
        sb.AppendLine("    int SampleRateHz);");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated catalog of bundled speech models.</summary>");
        sb.AppendLine("public static partial class SpeechModelCatalog");
        sb.AppendLine("{");

        var defaultId = NovolisAudioSpeechModelsManifest.DefaultSttProfileId;
        foreach (var entry in NovolisAudioSpeechModelsManifest.Bundled)
        {
            var field = ToFieldName(entry.Id);
            sb.AppendLine($"    /// <summary>{EscapeXml(entry.Id)} bundled speech model profile.</summary>");
            sb.AppendLine($"    public static SpeechModelProfile {field} => new(\"{entry.Id}\");");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>Default STT profile.</summary>");
        sb.AppendLine($"    public static SpeechModelProfile DefaultSttProfile => {ToFieldName(defaultId)};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Default STT profile id string.</summary>");
        sb.AppendLine($"    public const string DefaultSttProfileId = \"{defaultId}\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>All bundled speech models from the manifest.</summary>");
        sb.AppendLine("    public static IReadOnlyList<BundledSpeechModel> All { get; } =");
        sb.AppendLine("    [");
        foreach (var entry in NovolisAudioSpeechModelsManifest.Bundled)
        {
            sb.AppendLine("        new(");
            sb.AppendLine($"            {ToFieldName(entry.Id)},");
            sb.AppendLine($"            SpeechModelEngine.{entry.Engine},");
            sb.AppendLine($"            \"{entry.RepoFolder}\",");
            sb.AppendLine($"            {entry.SampleRateHz}),");
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Looks up a bundled model by profile id.</summary>");
        sb.AppendLine("    public static bool TryGet(SpeechModelProfile profile, out BundledSpeechModel model)");
        sb.AppendLine("        => TryGet(profile.Id, out model);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Looks up a bundled model by profile id string.</summary>");
        sb.AppendLine("    public static bool TryGet(string? profileId, out BundledSpeechModel model)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(profileId))");
        sb.AppendLine("        {");
        sb.AppendLine("            model = default;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var candidate in All)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.Equals(candidate.Profile.Id, profileId, StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("            {");
        sb.AppendLine("                model = candidate;");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        model = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Resolves the repo folder name for a profile.</summary>");
        sb.AppendLine("    public static string ResolveRepoFolder(SpeechModelProfile profile)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!profile.IsEmpty && TryGet(profile, out var model))");
        sb.AppendLine("            return model.RepoFolder;");
        sb.AppendLine($"        return TryGet(DefaultSttProfile, out model) ? model.RepoFolder : \"{defaultId}\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string ComputeManifestSha256(string repoRoot)
    {
        var paths = SpeechManifestInputPaths.AllManifestSourceFiles(repoRoot);
        using var sha = SHA256.Create();
        using var stream = new MemoryStream();
        foreach (var relative in paths)
        {
            var bytes = Encoding.UTF8.GetBytes(relative);
            stream.Write(bytes);
            stream.WriteByte((byte)'\n');
            var full = Path.Combine(repoRoot, relative.Replace('/', Path.DirectorySeparatorChar));
            var content = File.ReadAllBytes(full);
            stream.Write(content);
        }

        stream.Position = 0;
        return Convert.ToHexString(sha.ComputeHash(stream)).ToLowerInvariant();
    }

    private static string ToFieldName(string id)
    {
        var parts = id.Split('-', StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0)
                continue;
            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
                sb.Append(part.AsSpan(1));
        }

        return sb.Length > 0 ? sb.ToString() : "Unknown";
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);
}
