<Project>
  <PropertyGroup>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsTestingPlatformApplication>true</IsTestingPlatformApplication>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)..\..\novolis-governance\build\Novolis.OneTypePerFile.props" Condition="Exists('$(MSBuildThisFileDirectory)..\..\novolis-governance\build\Novolis.OneTypePerFile.props')" />
</Project>
