// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Audio.Pipeline -- run generate
// ManifestSha256: b7a1c023f602bce384998f26e63f45fa8b75566e6b8a31bb8746d931a337af40
#nullable enable
using Novolis.Audio.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Audio.Runtime;
/// <summary>
/// Global audio device lifecycle (miniaudio engine).
/// </summary>
public static partial class AudioDevice
{
    /// <summary>
    /// Initialize the global audio engine.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Init() => NovolisAudioNative.na_Init();
    /// <summary>
    /// Shut down the engine.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Uninit() => NovolisAudioNative.na_Uninit();
    /// <summary>
    /// Set master output volume.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetMasterVolume(float volume) => NovolisAudioNative.na_SetMasterVolume(volume);
}
