// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Audio.Pipeline -- run generate
// ManifestSha256: 95dd31d715a2c2a38ccc6fb05c0a20fb3aaaeebffc60d2428dff10af9026b118
#nullable enable

namespace Novolis.Audio.Voice;

/// <summary>Sherpa-ONNX speech engine kind for a bundled model.</summary>
public enum SpeechModelEngine
{
    /// <summary>SherpaOnnxSileroVad.</summary>
    SherpaOnnxSileroVad = 0,
    /// <summary>SherpaOnnxWhisper.</summary>
    SherpaOnnxWhisper = 1,
}

/// <summary>Metadata for a bundled speech model declared in the speech models manifest.</summary>
public readonly record struct BundledSpeechModel(
    SpeechModelProfile Profile,
    SpeechModelEngine Engine,
    string RepoFolder,
    int SampleRateHz);

/// <summary>Generated catalog of bundled speech models.</summary>
public static partial class SpeechModelCatalog
{
    /// <summary>silero-vad bundled speech model profile.</summary>
    public static SpeechModelProfile SileroVad => new("silero-vad");

    /// <summary>en-whisper-tiny bundled speech model profile.</summary>
    public static SpeechModelProfile EnWhisperTiny => new("en-whisper-tiny");

    /// <summary>Default STT profile.</summary>
    public static SpeechModelProfile DefaultSttProfile => EnWhisperTiny;

    /// <summary>Default STT profile id string.</summary>
    public const string DefaultSttProfileId = "en-whisper-tiny";

    /// <summary>All bundled speech models from the manifest.</summary>
    public static IReadOnlyList<BundledSpeechModel> All { get; } =
    [
        new(
            SileroVad,
            SpeechModelEngine.SherpaOnnxSileroVad,
            "silero-vad",
            16000),
        new(
            EnWhisperTiny,
            SpeechModelEngine.SherpaOnnxWhisper,
            "en-whisper-tiny",
            16000),
    ];

    /// <summary>Looks up a bundled model by profile id.</summary>
    public static bool TryGet(SpeechModelProfile profile, out BundledSpeechModel model)
        => TryGet(profile.Id, out model);

    /// <summary>Looks up a bundled model by profile id string.</summary>
    public static bool TryGet(string? profileId, out BundledSpeechModel model)
    {
        if (string.IsNullOrWhiteSpace(profileId))
        {
            model = default;
            return false;
        }

        foreach (var candidate in All)
        {
            if (string.Equals(candidate.Profile.Id, profileId, StringComparison.OrdinalIgnoreCase))
            {
                model = candidate;
                return true;
            }
        }

        model = default;
        return false;
    }

    /// <summary>Resolves the repo folder name for a profile.</summary>
    public static string ResolveRepoFolder(SpeechModelProfile profile)
    {
        if (!profile.IsEmpty && TryGet(profile, out var model))
            return model.RepoFolder;
        return TryGet(DefaultSttProfile, out model) ? model.RepoFolder : "en-whisper-tiny";
    }
}
