// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Audio.Pipeline -- run generate
// ManifestSha256: 0d431693637299de15f1564c3c491728bf24ffa9f365c990f77e6e2c0ed74079
#nullable enable

namespace Novolis.Audio.Voice;

/// <summary>Sherpa-ONNX offline TTS engine kind for a bundled model.</summary>
public enum VoiceModelEngine
{
    /// <summary>SherpaOnnxVitsPiper.</summary>
    SherpaOnnxVitsPiper = 0,
    /// <summary>KokoroOnnx.</summary>
    KokoroOnnx = 1,
}

/// <summary>Metadata for a bundled voice model declared in the voice models manifest.</summary>
/// <param name="Profile">Model profile id.</param>
/// <param name="Engine">Sherpa engine kind.</param>
/// <param name="RepoFolder">Folder under <c>models/</c> in the repository and NuGet content.</param>
/// <param name="OnnxFileName">Primary ONNX file name.</param>
/// <param name="SampleRateHz">Output PCM sample rate.</param>
/// <param name="EspeakVoice">espeak-ng voice id.</param>
public readonly record struct BundledVoiceModel(
    VoiceModelProfile Profile,
    VoiceModelEngine Engine,
    string RepoFolder,
    string OnnxFileName,
    int SampleRateHz,
    string EspeakVoice);

/// <summary>Generated catalog of bundled voice models.</summary>
public static partial class VoiceModelCatalog
{
    /// <summary>en-us-piper-amy bundled model profile.</summary>
    public static VoiceModelProfile EnUsPiperAmy => new("en-us-piper-amy");

    /// <summary>en-us-piper-lessac-low bundled model profile.</summary>
    public static VoiceModelProfile EnUsPiperLessacLow => new("en-us-piper-lessac-low");

    /// <summary>en-us-piper-kristin-medium bundled model profile.</summary>
    public static VoiceModelProfile EnUsPiperKristinMedium => new("en-us-piper-kristin-medium");

    /// <summary>Default bundled model profile.</summary>
    public static VoiceModelProfile DefaultProfile => EnUsPiperAmy;

    /// <summary>Default profile id string.</summary>
    public const string DefaultProfileId = "en-us-piper-amy";

    /// <summary>All bundled models from the manifest.</summary>
    public static IReadOnlyList<BundledVoiceModel> All { get; } =
    [
        new(
            EnUsPiperAmy,
            VoiceModelEngine.SherpaOnnxVitsPiper,
            "en-us-piper-amy",
            "en_US-amy-low.onnx",
            16000,
            "en-us"),
        new(
            EnUsPiperLessacLow,
            VoiceModelEngine.SherpaOnnxVitsPiper,
            "en-us-piper-lessac-low",
            "en_US-lessac-low.onnx",
            16000,
            "en-us"),
        new(
            EnUsPiperKristinMedium,
            VoiceModelEngine.SherpaOnnxVitsPiper,
            "en-us-piper-kristin-medium",
            "en_US-kristin-medium.onnx",
            22050,
            "en"),
    ];

    /// <summary>Looks up a bundled model by profile id.</summary>
    public static bool TryGet(VoiceModelProfile profile, out BundledVoiceModel model)
        => TryGet(profile.Id, out model);

    /// <summary>Looks up a bundled model by profile id string.</summary>
    public static bool TryGet(string? profileId, out BundledVoiceModel model)
    {
        if (string.IsNullOrWhiteSpace(profileId))
        {
            model = default;
            return false;
        }

        foreach (var candidate in All)
        {
            if (string.Equals(candidate.Profile.Id, profileId, StringComparison.OrdinalIgnoreCase))
            {
                model = candidate;
                return true;
            }
        }

        model = default;
        return false;
    }

    /// <summary>Resolves the repo/NuGet folder name for a profile, or the default when unset.</summary>
    public static string ResolveRepoFolder(VoiceModelProfile profile)
    {
        if (!profile.IsEmpty && TryGet(profile, out var model))
            return model.RepoFolder;
        return TryGet(DefaultProfile, out model) ? model.RepoFolder : "en-us-piper-amy";
    }
}
