// <auto-generated />
// Regenerate: dotnet run --project codegen/Novolis.Audio.Pipeline -- run generate
// ManifestSha256: b7a1c023f602bce384998f26e63f45fa8b75566e6b8a31bb8746d931a337af40
#nullable enable
using Novolis.Audio.Interop;
using System.Runtime.CompilerServices;

namespace Novolis.Audio.Runtime;
/// <summary>
/// Load and play decoded audio files.
/// </summary>
public static partial class Sound
{
    /// <summary>
    /// Load a sound from disk.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static nint Load(string path) => NovolisAudioNative.na_LoadSound(path);
    /// <summary>
    /// Release a loaded sound.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Unload(nint handle) => NovolisAudioNative.na_UnloadSound(handle);
    /// <summary>
    /// Start playback.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Play(nint handle) => NovolisAudioNative.na_PlaySound(handle);
    /// <summary>
    /// Stop playback.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Stop(nint handle) => NovolisAudioNative.na_StopSound(handle);
    /// <summary>
    /// Whether the sound is playing.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsPlaying(nint handle) => NovolisAudioNative.na_IsSoundPlaying(handle);
    /// <summary>
    /// Set per-sound volume.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void SetVolume(nint handle, float volume) => NovolisAudioNative.na_SetSoundVolume(handle, volume);
}
