<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Novolis.Audio.CodeGen</RootNamespace>
    <AssemblyName>Novolis.Audio.CodeGen.Abstractions</AssemblyName>
    <Description>Shared audio codegen contracts.</Description>
  </PropertyGroup>

  <ItemGroup>
    <LibraryReference Include="Novolis.CodeGen.Bindings" />
    <LibraryReference Include="Novolis.CodeGen.Bindings.Roslyn" />
    <LibraryReference Include="Novolis.CodeGen.Pipeline" />
  </ItemGroup>

</Project>
